services:
  - type: web
    name: meu-app-flet
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "flet run main.py --web --port $PORT"
    plan: free
    autoDeploy: true
